# Warning: this name must stay in sync with the badges referenced in the README
name: 'tests Mac'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install python3 curl pkg-config sdl2 ffmpeg glm spirv-cross ninja bash coreutils

    - name: Build
      run: |
        ./configure.py --buildtype debug --debug-opts gl gpu_capture --enable-ngfx-backend
        make

    - name: Python import and dylib runtime test
      run: |
        . venv/bin/activate
        python -c 'import pynodegl, pynodegl_utils'
        ngl-python -h

    - uses: actions/upload-artifact@v2
      if: always()
      with:
          name: nodegl-mac-build-logs
          path: |
            builddir/**/*.txt
            builddir/**/*.cmake
            builddir/**/*.log
            builddir/Makefile
